compatible version
eXist-db/crypto-exist-java-lib pull request #36
Opened 2021-06-02 17:35 UTC by line-o

crypto lib compatible with the coming version of eXist-db (5.3.0)

2021-06-02 18:03 UTC, joewiz commented
Thank you, @chakl and @line-o!

Is there a reason the PR is against the eXist-5.3.0 branch instead of master?

Could you confirm what the minimum eXist compatible version is now?

Also, once this is merged and published, do you recommend that we pull the "v5.3.0" version from the public repo? I recall this was known to be incompatible with eXist 5.x, despite its dependency declarations. http://exist-db.org/exist/apps/public-repo/packages/expath-crypto-exist-lib.html?eXist-db-min-version=4.4.0

2021-06-03 07:08 UTC, line-o commented
Version 5.3.0 of the crypto lib was, despite not being built from this repository, overwritten with a package that was version 1.0.0 with its version bumped. 
Pulling this package from the public repository was vetoed from the community.
The new version will therefore be 6.0.0 and will have a minimum processor dependency of 5.3.0

2021-06-07 19:06 UTC, adamretter commented on pom.xml
Did you mean to change the file perms on several of the files in the PR from 0644 -> 0755? I am not sure why you would want the execute bits set on non-executable files?

2021-06-07 19:10 UTC, adamretter requested changes

2021-06-07 19:10 UTC, adamretter commented on .classpath
> +			<attribute name="test" value="true"/>
Eclipse Project files should not be in SCM. Can you remove them and also add appropriate rules to your `.gitignore` please?

2021-06-07 19:24 UTC, line-o commented on .classpath
> +			<attribute name="test" value="true"/>
I do not really understand why this is worthy to block the merge of this PR.
As only one line was added (by @claudius108) it is clear that this file was in version control before.

2021-06-07 19:26 UTC, line-o commented on pom.xml
Yeah, I noticed those permission changes as well. But the goal of this commit is to make progress. 
As already discussed in a previous community call this package will be replaced by a version making use of the cryptographic capabilities bundled with exist in the foreseeable future.

2021-06-07 19:27 UTC, line-o commented on pom.xml
Changing them would not be a big of a deal.

2021-06-07 19:28 UTC, line-o commented on .classpath
> +			<attribute name="test" value="true"/>
in this commit 2a0cf88cde5cd412c48ea5ef1c3dd07a960d20e3

2021-06-11 10:37 UTC, line-o commented
This PR needs to be closed as its target branch is master and not existdb 5.3.0

2021-06-11 11:05 UTC, line-o commented
Superseded by #37

2021-06-11 11:05 UTC, closed without merging